### ISSUE TITLE
Any possibility of exposing Hue smart button long press for automation?

### ISSUE THREAD

**Issue by jdshkolnik** [ebaauw/homebridge-hue2#1]
Hi @ebaauw,

As it stands, the only thing we can set via HomeKit is single press of the [Hue Smart Button](https://www.philips-hue.com/en-us/p/hue-smart-button/046677553715). It'd be great if we could set the action for long press (cycle through single press would be nice, too). Do you think this is possible?

**Comment by ebaauw** [comment]
Homebridge Hue has been providing that for a long time, pretty much as soon as I got my hands on the smart button.  See https://github.com/ebaauw/homebridge-hue/wiki/Features.

**Comment by jdshkolnik** [comment]
Which sensor type does the button fall under? Perhaps I excluded it unintentionally.

**Comment by ebaauw** [comment]
ZLLSwitch

**Comment by jdshkolnik** [comment]
Ok, yeah, that's on me. I was excluding ZLLSwitch for a long time because it was just noise...up until it wasn't. Sorry for the waste of time. Thank you very much.
